// js/roster.js — GENERATED by tools/gen/gen-shell.mjs from tools/manifest.cjs. Do not edit.
// The tagless rosters js/game.js injects at runtime (deferred backends, the
// agent surface, the race payload, the data hub, the multiplayer stack) and
// the eval-order edges inside each. Edit the manifest, then regenerate.
(function () {
  "use strict";
  self.ApexRoster = Object.freeze({
    DEFERRED: {},
    DEFERRED_EDGES: [],
    LAZY_AGENT: [
    "js/agent/agentview-raster.js",
    "js/agent/agentview.js",
    "js/agent/apex.js"
  ],
    LAZY_EDGES: [
    [
      "js/agent/agentview-raster.js",
      "js/agent/agentview.js"
    ]
  ],
    LAZY_RACE: [
    "js/lighting/presets.js"
  ],
    SCENERY_DIR: "js/circuits/scenery",
    LAZY_DATA: [
    "js/data/api.js",
    "js/data/telemetry.js",
    "js/data/export.js",
    "js/data/schedule.js",
    "js/data/standings.js",
    "js/data/lastrace.js",
    "js/data/live.js",
    "js/data/hub.js"
  ],
    LAZY_DATA_EDGES: [
    [
      "js/data/api.js",
      "js/data/hub.js"
    ],
    [
      "js/data/telemetry.js",
      "js/data/hub.js"
    ],
    [
      "js/data/export.js",
      "js/data/hub.js"
    ],
    [
      "js/data/schedule.js",
      "js/data/hub.js"
    ],
    [
      "js/data/standings.js",
      "js/data/hub.js"
    ],
    [
      "js/data/lastrace.js",
      "js/data/hub.js"
    ],
    [
      "js/data/live.js",
      "js/data/hub.js"
    ]
  ],
    LAZY_NET: [
    "js/net/nostr.js",
    "js/net/rendezvous.js",
    "js/net/sdp.js",
    "js/net/qr.js",
    "js/net/scan.js",
    "js/net/transport.js",
    "js/net/handshake.js",
    "js/net/snapshot.js",
    "js/net/session.js",
    "js/net/netplay.js",
    "js/net/lobby.js"
  ],
    LAZY_NET_EDGES: [
    [
      "js/net/snapshot.js",
      "js/net/session.js"
    ],
    [
      "js/net/sdp.js",
      "js/net/handshake.js"
    ],
    [
      "js/net/qr.js",
      "js/net/lobby.js"
    ],
    [
      "js/net/rendezvous.js",
      "js/net/lobby.js"
    ],
    [
      "js/net/nostr.js",
      "js/net/rendezvous.js"
    ],
    [
      "js/net/scan.js",
      "js/net/lobby.js"
    ]
  ],
  });
})();
