// js/roster.js — GENERATED by tools/gen-shell.mjs from tools/manifest.cjs. Do not edit.
// The tagless rosters js/game.js injects at runtime (deferred backends, the
// agent surface, the race payload, the data hub, the multiplayer stack) and
// the eval-order edges inside each. Edit the manifest, then regenerate.
(function () {
  "use strict";
  self.ApexRoster = Object.freeze({
    DEFERRED: {
    "webgpu": [
      "js/render/webgpu/wgsl-chunks.js",
      "js/render/webgpu/wgsl-post.js",
      "js/render/webgpu/wgsl-fx.js",
      "js/render/webgpu/wgx.js"
    ],
    "three": [
      "js/render/three/tsl-chunks.js",
      "js/render/three/tsl-lit.js",
      "js/render/three/tsl-sky.js",
      "js/render/three/tsl-fx.js",
      "js/render/three/tsl-post.js",
      "js/render/three/tlx-shadow.js",
      "js/render/three/tlx-chunked.js",
      "js/render/three/tlx-post.js",
      "js/render/three/tlx.js"
    ]
  },
    DEFERRED_EDGES: [
    [
      "js/render/webgpu/wgsl-chunks.js",
      "js/render/webgpu/wgsl-post.js"
    ],
    [
      "js/render/webgpu/wgsl-chunks.js",
      "js/render/webgpu/wgsl-fx.js"
    ],
    [
      "js/render/webgpu/wgsl-post.js",
      "js/render/webgpu/wgx.js"
    ],
    [
      "js/render/webgpu/wgsl-fx.js",
      "js/render/webgpu/wgx.js"
    ],
    [
      "js/render/three/tsl-chunks.js",
      "js/render/three/tsl-lit.js"
    ],
    [
      "js/render/three/tsl-lit.js",
      "js/render/three/tlx.js"
    ],
    [
      "js/render/three/tsl-sky.js",
      "js/render/three/tlx.js"
    ],
    [
      "js/render/three/tsl-fx.js",
      "js/render/three/tlx.js"
    ],
    [
      "js/render/three/tlx-shadow.js",
      "js/render/three/tlx.js"
    ],
    [
      "js/render/three/tlx-chunked.js",
      "js/render/three/tlx.js"
    ],
    [
      "js/render/three/tsl-post.js",
      "js/render/three/tlx-post.js"
    ],
    [
      "js/render/three/tlx-post.js",
      "js/render/three/tlx.js"
    ]
  ],
    LAZY_AGENT: [
    "js/game/agentview-raster.js",
    "js/game/agentview.js",
    "js/game/apex.js"
  ],
    LAZY_EDGES: [
    [
      "js/game/agentview-raster.js",
      "js/game/agentview.js"
    ]
  ],
    LAZY_RACE: [
    "js/game/light-presets.js"
  ],
    SCENERY_DIR: "js/circuits/scenery",
    LAZY_DATA: [
    "js/data/api.js",
    "js/data/telemetry.js",
    "js/data/export.js",
    "js/data/schedule.js",
    "js/data/standings.js",
    "js/data/lastrace.js",
    "js/data/live.js",
    "js/data/hub.js"
  ],
    LAZY_DATA_EDGES: [
    [
      "js/data/api.js",
      "js/data/hub.js"
    ],
    [
      "js/data/telemetry.js",
      "js/data/hub.js"
    ],
    [
      "js/data/export.js",
      "js/data/hub.js"
    ],
    [
      "js/data/schedule.js",
      "js/data/hub.js"
    ],
    [
      "js/data/standings.js",
      "js/data/hub.js"
    ],
    [
      "js/data/lastrace.js",
      "js/data/hub.js"
    ],
    [
      "js/data/live.js",
      "js/data/hub.js"
    ]
  ],
    LAZY_NET: [
    "js/net/nostr.js",
    "js/net/rendezvous.js",
    "js/net/sdp.js",
    "js/net/qr.js",
    "js/net/scan.js",
    "js/net/transport.js",
    "js/net/handshake.js",
    "js/net/snapshot.js",
    "js/net/session.js",
    "js/net/netplay.js",
    "js/net/lobby.js"
  ],
    LAZY_NET_EDGES: [
    [
      "js/net/snapshot.js",
      "js/net/session.js"
    ],
    [
      "js/net/sdp.js",
      "js/net/handshake.js"
    ],
    [
      "js/net/qr.js",
      "js/net/lobby.js"
    ],
    [
      "js/net/rendezvous.js",
      "js/net/lobby.js"
    ],
    [
      "js/net/nostr.js",
      "js/net/rendezvous.js"
    ],
    [
      "js/net/scan.js",
      "js/net/lobby.js"
    ]
  ],
  });
})();
