#!/usr/bin/env python3
"""@doc Measure every shipped font's DIGIT ADVANCES and OpenType figure features
into tests/data/font-digits.json, the ledger tests/unit/font-digits.test.mjs
asserts against.

WHY A LEDGER AND NOT A LIVE CHECK. `font-variant-numeric: tabular-nums` appears
~36 times on --font-hud and every one of them is inert, because Rajdhani's Latin
subset carries no OpenType features at all: the full TTF has 13, all registered
under script `deva`, and Google's subsetter drops them for the Latin range. CSS
cannot synthesise a feature a font lacks and says nothing when it fails, so the
declaration reads as working. @supports cannot catch it either — the PROPERTY is
supported; the FONT is what is missing.

The test suite is Node and a .woff2 is Brotli with a transformed table directory,
so parsing one in-process would mean a new dependency. Measuring here with
fontTools and COMMITTING the numbers keeps the check honest in the one way that
matters: a font added without re-running this has no ledger entry and the test
fails. It cannot go quietly green, which is exactly how the original bug hid.
(Same shape as tests/data/ratchets.json — a measured ledger, not a live probe.)

Needs fontTools (`pip install fonttools brotli`). Not part of CI; run it when the
fonts change, like `ratchets.mjs --update`.

    python3 tools/check/font-digits.py            # rewrite the ledger
    python3 tools/check/font-digits.py --check    # exit 1 if stale
"""
import json, pathlib, sys

try:
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit("fontTools missing: pip install fonttools brotli")

ROOT = pathlib.Path(__file__).resolve().parents[2]
FONTS = ROOT / "assets" / "fonts"
LEDGER = ROOT / "tests" / "data" / "font-digits.json"
DIGITS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]


def feature_tags(font, table):
    """Every feature tag in GSUB/GPOS, and the scripts they are registered under."""
    if table not in font:
        return [], []
    t = font[table].table
    feats = sorted({f.FeatureTag for f in t.FeatureList.FeatureRecord}) if t.FeatureList else []
    scripts = sorted({s.ScriptTag for s in t.ScriptList.ScriptRecord}) if t.ScriptList else []
    return feats, scripts


def tnum_advances(font, base):
    """Resolve `tnum`'s single substitutions and return the substituted advances."""
    gsub = font.get("GSUB")
    if not gsub or not gsub.table.FeatureList:
        return None
    hmtx, mapping = font["hmtx"], {}
    for rec in gsub.table.FeatureList.FeatureRecord:
        if rec.FeatureTag != "tnum":
            continue
        for li in rec.Feature.LookupListIndex:
            for sub in gsub.table.LookupList.Lookup[li].SubTable:
                mapping.update(getattr(sub, "mapping", {}) or {})
    if not mapping:
        return None
    return [hmtx[mapping.get(g, g)][0] for g in base]


def measure(path):
    font = TTFont(path, lazy=True)
    upem = font["head"].unitsPerEm
    hmtx = font["hmtx"]
    glyphs = set(font.getGlyphOrder())
    # Fall back through cmap for fonts that do not use the standard glyph names.
    cmap = font.getBestCmap()
    names = [g if g in glyphs else cmap.get(0x30 + i) for i, g in enumerate(DIGITS)]
    if any(n is None for n in names):
        return {"error": "digits 0-9 not all present"}
    adv = [hmtx[n][0] for n in names]
    gsub_f, gsub_s = feature_tags(font, "GSUB")
    gpos_f, gpos_s = feature_tags(font, "GPOS")
    tnum = tnum_advances(font, names)
    out = {
        "unitsPerEm": upem,
        "digitAdvances": adv,
        "digitsUniform": len(set(adv)) == 1,
        "widestDigitEm": round(max(adv) / upem, 6),
        "gsubFeatures": gsub_f, "gsubScripts": gsub_s,
        "gposFeatures": gpos_f, "gposScripts": gpos_s,
        "hasTnum": "tnum" in gsub_f,
    }
    if tnum is not None:
        out["tnumAdvances"] = tnum
        out["tnumUniform"] = len(set(tnum)) == 1
    return out


def build():
    files = sorted(p.name for p in FONTS.glob("*.woff2"))
    return {
        "_comment": "GENERATED by tools/check/font-digits.py — do not hand-edit. "
                    "Re-run it when assets/fonts/ changes; tests/unit/font-digits.test.mjs "
                    "fails on any font missing an entry, so a new font cannot ship unmeasured.",
        "fonts": {f: measure(FONTS / f) for f in files},
    }


if __name__ == "__main__":
    data = build()
    if "--check" in sys.argv:
        cur = json.loads(LEDGER.read_text()) if LEDGER.exists() else None
        if cur != data:
            sys.exit("tests/data/font-digits.json is stale — run tools/check/font-digits.py")
        print("font-digits ledger: up to date")
    else:
        LEDGER.write_text(json.dumps(data, indent=1) + "\n")
        print(f"tests/data/font-digits.json: {len(data['fonts'])} font(s)")
        for name, m in data["fonts"].items():
            flag = "uniform" if m.get("digitsUniform") else ("tnum->uniform" if m.get("tnumUniform") else "PROPORTIONAL, no tnum")
            print(f"  {name:<44} {flag}")
