#!/usr/bin/env node
// session-status.mjs — the session's handoff block, GENERATED from git and the logs, never hand-kept.
// @doc Prints this branch's handoff block (sessions from `Claude-Session:` trailers, commits vs the deploy branch, dirty/unpushed state, each test log's verdict, a live run) as Markdown for the draft PR body, or `--json`.
// @skill check-changes
//
// AGENTS.md §The loop: every session pushes its claude/<topic> branch and keeps
// a DRAFT PR open, and the PR description is the handoff another agent reads.
// Half of a handoff is facts git already holds — which sessions worked here
// (the `Claude-Session:` trailer every commit carries), what landed, what is
// uncommitted or unpushed, what each test log concluded. A hand-maintained
// session log re-types those facts, drifts from them, and on a shared branch
// conflicts with every other session's log. So this prints them; the agent
// writes only what git cannot know (goal, next step, open question) around it.
//
//   node tools/ci/session-status.mjs            # Markdown block for the PR body
//   node tools/ci/session-status.mjs --json     # the same, as data
//
// Reads only: local git (no fetch — run `git fetch origin <deploy>` first for a
// fresh ahead/behind), artifacts/logs/*.log, and .claude/hooks/live-run.py.
// Exit 0 always.
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const DEPLOY = "claude/f1-game-project-26h3ng";

const git = (...args) => {
  const r = spawnSync("git", args, { cwd: ROOT, encoding: "utf8" });
  return r.status === 0 ? r.stdout.trim() : "";
};

/** The LAST verdict line a runner wrote: the Playwright reporter's `= run <s>`,
 *  tooling-fast's `[tooling-fast] = run <s>`, or test-bg's `= bg exit N` trailer
 *  (the only line a run that died before its reporter's summary still has). */
export function parseVerdict(text) {
  let last = null;
  for (const line of String(text).split("\n")) {
    const m = line.match(/= run (passed|failed|timedout|interrupted)\b(.*)$/);
    if (m) { last = `${m[1]}${m[2].trim() ? " " + m[2].trim() : ""}`; continue; }
    const b = line.match(/^= bg exit (\d+)\s*$/);
    if (b && !last) last = b[1] === "0" ? "exited 0 (no reporter summary)" : `exited ${b[1]} (no reporter summary)`;
  }
  return last || "no verdict yet (running, or died before its summary)";
}

export function collect() {
  const branch = git("rev-parse", "--abbrev-ref", "HEAD") || "?";
  const base = git("rev-parse", "--verify", "-q", `origin/${DEPLOY}`) ? `origin/${DEPLOY}` : "";
  const [behind, ahead] = base
    ? (git("rev-list", "--left-right", "--count", `${base}...HEAD`).split(/\s+/).map(Number))
    : [null, null];
  const range = base ? `${base}..HEAD` : "HEAD~10..HEAD";
  const commits = git("log", "--format=%h%x09%s", range).split("\n").filter(Boolean)
    .map((l) => { const [sha, ...s] = l.split("\t"); return { sha, subject: s.join("\t") }; });
  const sessions = [...new Set(git("log", "--format=%(trailers:key=Claude-Session,valueonly)", range)
    .split("\n").map((s) => s.trim()).filter(Boolean))];
  const upstream = git("rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}");
  const unpushed = upstream ? Number(git("rev-list", "--count", `${upstream}..HEAD`)) || 0 : null;
  const dirty = git("status", "--porcelain").split("\n").filter(Boolean);
  const logDir = path.join(ROOT, "artifacts/logs");
  const logs = fs.existsSync(logDir)
    ? fs.readdirSync(logDir).filter((f) => f.endsWith(".log")).map((f) => {
        const abs = path.join(logDir, f);
        const st = fs.statSync(abs);
        return { log: `artifacts/logs/${f}`, verdict: parseVerdict(fs.readFileSync(abs, "utf8")),
                 ageMin: Math.round((Date.now() - st.mtimeMs) / 60000) };
      }).sort((a, b) => a.ageMin - b.ageMin)
    : [];
  const lr = spawnSync("python3", [path.join(ROOT, ".claude/hooks/live-run.py"), ROOT], { encoding: "utf8" });
  const live = (lr.stdout || "").trim() || null;
  return { at: new Date().toISOString(), branch, base: base || null, ahead, behind, unpushed,
           upstream: upstream || null, sessions, commits, dirty, logs, live };
}

export function toMarkdown(s) {
  const out = [];
  out.push(`### Status (generated by \`node tools/ci/session-status.mjs\` at ${s.at})`);
  out.push("");
  out.push(`- **Branch** \`${s.branch}\`` + (s.base ? ` — ${s.ahead} ahead / ${s.behind} behind \`${s.base}\`` : " — deploy branch not fetched"));
  out.push(`- **Pushed** ${s.upstream == null ? "no upstream — `git push -u origin " + s.branch + "`" : s.unpushed ? `${s.unpushed} commit(s) NOT pushed` : "yes"}`);
  out.push(`- **Working tree** ${s.dirty.length ? `${s.dirty.length} uncommitted: ${s.dirty.slice(0, 8).map((d) => "`" + d.slice(3) + "`").join(", ")}${s.dirty.length > 8 ? ", …" : ""}` : "clean"}`);
  out.push(`- **Live browser run** ${s.live ? "`" + s.live + "` — its verdict is NOT read yet" : "none"}`);
  out.push(`- **Sessions** ${s.sessions.length ? s.sessions.join(", ") : "none recorded (no Claude-Session trailers)"}`);
  out.push("");
  out.push(`**Commits** (${s.commits.length})`);
  for (const c of s.commits.slice(0, 20)) out.push(`- \`${c.sha}\` ${c.subject}`);
  if (s.commits.length > 20) out.push(`- … ${s.commits.length - 20} more`);
  out.push("");
  out.push("**Test logs** (newest first; a log is this container's, gone with it)");
  if (!s.logs.length) out.push("- none in artifacts/logs/");
  for (const l of s.logs.slice(0, 10)) out.push(`- \`${l.log}\` — ${l.verdict} (${l.ageMin} min ago)`);
  return out.join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const s = collect();
  console.log(process.argv.includes("--json") ? JSON.stringify(s, null, 2) : toMarkdown(s));
}
