// manifest.cjs — the single source of truth for script load order.
// @doc Load-order single source of truth: `FULL`, `DEFERRED`, `LAZY_AGENT`, `HARD_EDGES`, `TRACK_VM`; index.html must match.
// @skill check-changes
//
// index.html's tag blocks, tools/carview.html's tags, sw.js's optional
// precache seed and js/roster.js (the lazy rosters js/game.js injects) are all
// GENERATED from this file by tools/gen/gen-shell.mjs; tests/unit/load-order.test.mjs
// asserts the generated blocks are byte-identical to a fresh run. Node VM
// loaders (verify-track.cjs, the track-foundation tests) iterate the subsets
// below instead of keeping their own copies, so adding/moving a file is a
// one-line edit here plus `node tools/gen/gen-shell.mjs`.
//
// Directory map (post-reorg):
//   js/render/    renderer: gfx façade, GLX (WebGL2), shaders, WebGPU backend
//   js/track/     track ENGINE + infra (geometry, surface, scenery kits)
//   js/circuits/  the 40 circuit DEFINITIONS (24 season + 16 classic; one file each)
//   js/car/       car model, liveries, parts, ghost, teams
//   js/data/      data hub (api client + tab modules + shell)
//   js/game/      game-support modules extracted from / loaded before game.js
//
// Rules encoded here:
//  - FULL is every TAGGED js/ file, in the exact index.html <script> order.
//  - DEFERRED is renderer backends with no tag, injected at runtime by
//    game.js when opted into. LAZY_AGENT is the __apex / agentview surface
//    (same "no tag" rule, but NOT SW-optional — V8 full-compiles install
//    puts). FULL ∪ DEFERRED ∪ LAZY_AGENT must cover js/**/*.js.
//  - The circuit tags ("@circuits") stay in their curated order — that
//    order IS Tracks.LIST, which is the track-picker order. The season
//    calendar is Tracks.SEASON, the `classic: false` prefix of that list, so
//    the 24 season circuits MUST stay first and in calendar order. Do not
//    sort or reorder them.
//  - A future generated js/track/circuit-elevations.js (tools/
//    bake-elevation.mjs) must slot immediately BEFORE js/track/tracks.js.
//  - HARD_EDGES are eval-time dependencies (destructure/call at IIFE
//    evaluation). Violating one is a ReferenceError at load, not a subtle bug.

"use strict";

// Curated circuit order (== Tracks.LIST == picker order).
// The first 24 are the season calendar (Tracks.SEASON, in round order); the
// retired circuits below carry `classic: true` and are appended, never
// interleaved — a stored apex26.track is a positional index into this list.
const CIRCUITS = [
  "bahrain", "monaco", "silverstone", "spa", "monza", "suzuka", "singapore",
  "cota", "interlagos", "vegas", "madrid", "zandvoort", "jeddah",
  "albert_park", "shanghai", "miami", "imola", "montreal", "redbull",
  "hungaroring", "baku", "mexico", "qatar", "abudhabi",
  // ── retired / off-calendar (classic: true) ──
  "hockenheim", "nurburgring", "catalunya", "sepang", "istanbul",
  "paul_ricard", "portimao", "sochi", "mugello", "magny_cours",
  "estoril", "kyalami", "watkins_glen", "indianapolis", "buenos_aires",
  "jacarepagua",
];

const CIRCUITS_DIR = "js/circuits";
const circuitFiles = CIRCUITS.map((id) => `${CIRCUITS_DIR}/${id}.js`);
// The bespoke scenery closure for each circuit, split out of its def file.
// ~27 KB each; all 40 were 1,083 KB of the boot script wall for a session that
// builds ONE circuit. No <script> tag — game.js fetches the one it is about to
// build (RACE_SCENERY / sceneryUrl), and js/track/tracks.js resolves through
// window.TrackScenery[def.id]. The Node build harnesses load the whole dir.
const SCENERY_DIR = "js/circuits/scenery";
const LAZY_SCENERY = CIRCUITS.map((id) => `${SCENERY_DIR}/${id}.js`);

// Every js file, in exact index.html <script> tag order.
const FULL = [
  // Log must be first: every module below may log at evaluation time.
  "js/core/log.js",
  "js/core/mat4.js",
  // GENERATED by tools/gen/gen-shell.mjs: the tagless rosters below (DEFERRED,
  // LAZY_*) as one frozen global, ApexRoster, read by js/game.js at eval.
  "js/roster.js",
  "js/render/glx/shaders/glsl-chunks.js",
  "js/render/glx/shaders/glsl-lit.js",
  "js/render/glx/shaders/glsl-sky.js",
  "js/render/glx/shaders/glsl-fx.js",
  "js/render/glx/shaders/glsl-post.js",
  "js/render/glx/post.js",
  "js/render/glx/shadow.js",
  "js/render/shared/lamp-chunks.js",
  "js/render/glx/chunked.js",
  "js/render/glx/glx.js",
  // NB: js/render/webgpu/* and js/render/three/* are NOT here — they are
  // DEFERRED (see below) and injected at boot only when opted into.
  "js/render/gfx.js",
  "js/render/shared/gltf.js",
  "js/render/shared/assets.js",
  "js/data/teams.js",
  "js/data/driver-ratings.js",
  // Persistence sits ahead of every js/game module: the settings panels, the
  // perf sentinel and the Spotify client go through GameStore.store's raw lane,
  // and spotify.js's init() runs at EVAL when the document is already complete
  // (the game-vm harness; a late-injected script), so the store must precede it.
  "js/core/store.js",
  "js/track/core/geom.js",
  "js/track/scenery/data.js",
  "js/track/core/space.js",
  "js/track/core/surface.js",
  "js/track/scenery/models.js",
  "js/track/scenery/graph.js",
  "js/track/scenery/themes.js",
  "js/track/scenery/landmark-kit.js",
  "js/track/scenery/circuit-kit.js",
  "js/track/core/spline.js",
  "js/track/core/mesh.js",
  "js/track/scenery/nature.js",
  "js/track/scenery/structures.js",
  "js/track/scenery/city.js",
  "js/track/scenery/identity.js",
  ...circuitFiles,
  "js/track/tracks.js",
  "js/ui/track-maps.js",
  "js/car/car3d.js",
  "js/input/input.js",
  "js/audio/engine.js",
  "js/audio/music-lib.js",
  "js/audio/spotify.js",
  "js/audio/panel.js",
  "js/car/parts.js",
  "js/car/liveries.js",
  "js/car/crest-paths.js",
  "js/car/liverytex.js",
  "js/car/ghost.js",
  "js/physics/consts.js",
  "js/lighting/knobs.js",
  "js/lighting/track-lights.js",
  "js/lighting/frame-lights.js",
  "js/lighting/lighting.js",
  "js/lighting/profiles.js",
  "js/car/car-mesh.js",
  "js/garage/scene.js",
  "js/physics/body-attitude.js",
  "js/fx/particles.js",
  "js/lighting/atmosphere.js",
  "js/career/career.js",
  "js/career/season-cal.js",
  "js/race/reliability.js",
  "js/physics/ai-drive.js",
  "js/camera/offsets.js",
  "js/garage/setup-sheet.js",
  "js/career/career-ui.js",
  "js/career/season-ui.js",
  "js/ui/select-screen.js",
  "js/ui/scroll-fade.js",
  "js/ui/css-zoom.js",
  "js/ui/sheet-shape.js",
  "js/ui/layers.js",
  "js/ui/modal.js",
  "js/ui/menu-nav.js",
  "js/ui/aria-state.js",
  "js/ui/settings-tabs.js",
  "js/physics/aero-zones.js",
  "js/fx/skidmarks.js",
  "js/race/race-control.js",
  "js/camera/photo-cam.js",
  "js/lighting/tuner-panel.js",
  "js/camera/tuner-panel.js",
  "js/physics/brake-cue.js",
  "js/input/steer-tuning.js",
  "js/perf/governor.js",
  "js/perf/loop-health.js",
  "js/perf/quality-preset.js",
  "js/perf/renderer-picker.js",
  "js/perf/gfx-debug-overlay.js",
  "js/ui/scale.js",
  "js/camera/cockpit-opts.js",
  "js/perf/metrics-overlay.js",
  "js/camera/vantage.js",
  "js/camera/mode-switch.js",
  "js/ui/hud.js",
  "js/ui/results-sheet.js",
  "js/race/quali-model.js",
  "js/ui/quali-sheet.js",
  "js/physics/debris-world.js",
  "js/physics/incident-sim.js",
  // agentview* + apex.js are LAZY_AGENT — injected when tests / localhost /
  // ?apex=1 ask for __apex. Not on the player boot wall (PWA memory).
  // Multiplayer wire. Pure logic with no game dependency, so position only
  // has to satisfy "before whatever consumes it" — game.js, last as always.
  "js/game.js",
];

// Stylesheet <link> order in index.html.
const CSS = [
  "css/tokens.css", "css/components.css", "css/tuner.css", "css/menus.css",
  "css/carsetup.css", "css/hud.css", "css/overlays.css", "css/responsive.css",
  "css/track-detail.css",   // link order == original style.css source order (cascade-preserving)
  "css/career.css",
  "css/data.css",
];
// The two title-critical sheets are also <link rel="preload">ed above the
// stylesheet block (gen-shell writes that block too).
const CSS_PRELOAD = ["css/tokens.css", "css/components.css"];
// Sheets that are NOT title-critical load print→all (media="print"
// onload="this.media='all'") so they do not hold LCP; the rest render-block.
const CSS_DEFERRED = [
  "css/tuner.css", "css/carsetup.css", "css/hud.css", "css/overlays.css",
  "css/track-detail.css", "css/career.css", "css/data.css",
];
// Hand comments gen-shell emits inside the index.html script block, keyed by
// the tag they sit before/after. Prose only — the tags themselves are FULL.
const SHELL_NOTES = {
  before: {
    "js/circuits/bahrain.js": "<!-- circuit definitions (data) — must load before the tracks engine -->",
  },
  after: {},
};

// tools/carview.html <script> subset, in order (paths repo-relative; the file
// itself uses ../js/... since it is served from /tools/).
const CARVIEW = [
  "js/core/log.js",
  "js/core/mat4.js",
  "js/render/glx/shaders/glsl-chunks.js",
  "js/render/glx/shaders/glsl-lit.js",
  "js/render/glx/shaders/glsl-sky.js",
  "js/render/glx/shaders/glsl-fx.js",
  "js/render/glx/shaders/glsl-post.js",
  "js/render/glx/post.js",
  "js/render/glx/shadow.js",
  "js/render/shared/lamp-chunks.js",
  "js/render/glx/chunked.js",
  "js/render/glx/glx.js",
  "js/data/teams.js",
  "js/car/parts.js",
  "js/car/car3d.js",
  "js/car/liveries.js",
  "js/car/crest-paths.js",
  "js/car/liverytex.js",
  "js/car/car-mesh.js",
];

// verify-track.cjs / track-foundation Node-VM subset, in order.
// "@circuits" expands to every file in CIRCUITS_DIR (readdir, sorted — VM
// verification is per-id, so LIST order does not matter there).
const TRACK_VM = [
  "js/core/log.js",
  // mat4.js is not matrix math for the VM's sake — it is the home of the shared
  // scalar helpers (M4.clamp/lerp/wrapDelta), which js/track/ binds at eval.
  // Leaving it out is how the track engine ended up with four private lerps.
  "js/core/mat4.js",
  "js/track/core/geom.js",
  "js/track/scenery/data.js",
  "js/track/core/space.js",
  "js/track/core/surface.js",
  "js/track/scenery/models.js",
  "js/track/scenery/graph.js",
  "js/track/scenery/themes.js",
  "js/track/scenery/landmark-kit.js",
  "js/track/scenery/circuit-kit.js",
  "js/track/core/spline.js",
  "js/track/core/mesh.js",
  "js/track/scenery/nature.js",
  "js/track/scenery/structures.js",
  "js/track/scenery/city.js",
  "js/track/scenery/identity.js",
  "@circuits",
  "js/track/tracks.js",
];

// Eval-time dependencies: [before, after]. Each pair must be ordered in FULL.
const HARD_EDGES = [
  // js/net's six intra-directory pairs moved to LAZY_NET_EDGES when the
  // multiplayer stack left FULL: a HARD_EDGES pair must have BOTH ends in FULL
  // to be orderable by tag position.
  ["js/core/mat4.js", "js/render/glx/glx.js"],                       // glx uses M4 at init
  // M4 is also the home of the shared scalar helpers (clamp/lerp/wrapDelta) and
  // every consumer ALIASES them at eval (`const clamp = M4.clamp;`). mat4.js is
  // the 2nd tag so the order is never in doubt, but these are real eval-time
  // edges and the list is what records them; the toposort check derives the rest.
  ["js/core/mat4.js", "js/game.js"],
  ["js/roster.js", "js/game.js"],                          // game.js reads ApexRoster's rosters at eval
  ["js/core/mat4.js", "js/track/core/spline.js"],
  ["js/core/mat4.js", "js/track/scenery/structures.js"],
  // ["js/core/mat4.js", "js/data/telemetry.js"] was here. telemetry.js is LAZY_DATA
  // now, so the pair crosses rosters and HARD_EDGES cannot order it. The
  // dependency is real and satisfied by CONSTRUCTION rather than by position:
  // mat4.js is the 2nd tag in FULL and the data bundle is injected from a menu
  // click, long after every tag has evaluated.
  // liverytex sizes its atlas from GLX.mobileTier at EVAL time — the one
  // mobile-tier detection now lives in glx.js and nowhere else.
  ["js/render/glx/glx.js", "js/car/liverytex.js"],
  // session.js decodes off the same channel as snapshot.js and shares its ONE
  // toView(); the two hand-rolled copies had already diverged over how a
  // DataView argument is handled, which is exactly the bug a shared helper
  // prevents. Call-time, not eval-time, but a session with no NetSnapshot
  // silently drops every state packet rather than throwing — so pin the order.
  // handshake.js calls NetSdp.packChecked/unpack whenever it builds or reads
  // an invite code. Call-time, but a handshake with no NetSdp throws inside
  // the click handler that generates the invite — the one place an error is
  // least visible.
  // lobby.js draws the invite QR through NetQr the moment an invite exists.
  // lobby.js calls NetRendezvous the moment a room-code button is wired.
  // rendezvous.js calls NetNostr whenever no private relay is configured,
  // which is the DEFAULT path — room codes work with nothing deployed.
  // lobby.js creates a NetScan the moment a SCAN button is wired.
  // chunks.js before every shader file (lit/sky/post interpolate GLXChunks at
  // eval; fx.js is chunk-free today but keeps the uniform ordering contract).
  ["js/render/glx/shaders/glsl-chunks.js", "js/render/glx/shaders/glsl-lit.js"],
  ["js/render/glx/shaders/glsl-chunks.js", "js/render/glx/shaders/glsl-sky.js"],
  ["js/render/glx/shaders/glsl-chunks.js", "js/render/glx/shaders/glsl-fx.js"],
  ["js/render/glx/shaders/glsl-chunks.js", "js/render/glx/shaders/glsl-post.js"],
  // every shader file before glx.js (it destructures GLXShaders at eval)
  ["js/render/glx/shaders/glsl-lit.js", "js/render/glx/glx.js"],
  ["js/render/glx/shaders/glsl-sky.js", "js/render/glx/glx.js"],
  ["js/render/glx/shaders/glsl-fx.js", "js/render/glx/glx.js"],
  ["js/render/glx/shaders/glsl-post.js", "js/render/glx/glx.js"],
  // glx/ subsystem modules before glx.js (GLX.init calls GLXPost/GLXShadow/
  // GLXChunked.init — call-time, but the globals must exist by then; keep the
  // ordering explicit)
  ["js/render/glx/post.js", "js/render/glx/glx.js"],
  ["js/render/glx/shadow.js", "js/render/glx/glx.js"],
  ["js/render/shared/lamp-chunks.js", "js/render/glx/chunked.js"], // drawChunked resolves LampChunks tables (call-time; keep explicit)
  ["js/render/glx/chunked.js", "js/render/glx/glx.js"],
  ["js/render/glx/glx.js", "js/render/shared/assets.js"],         // Assets feature-detects the backend's createTextureArray
  ["js/track/core/geom.js", "js/garage/scene.js"],          // the bay reads TrackGeom.MAT at eval for its per-vertex material ids
  ["js/track/core/geom.js", "js/track/tracks.js"],               // tracks destructures TrackGeom at eval
  ["js/track/core/spline.js", "js/track/tracks.js"],             // tracks destructures TrackSpline at eval
  ["js/track/core/geom.js", "js/track/core/mesh.js"],                 // mesh destructures TrackGeom at eval
  ["js/track/core/spline.js", "js/track/core/mesh.js"],               // mesh destructures TrackSpline at eval
  ["js/track/core/mesh.js", "js/track/tracks.js"],               // tracks destructures TrackMesh at eval
  ["js/track/scenery/graph.js", "js/track/tracks.js"],               // buildProps calls TrackGraph.create at build
  ["js/track/scenery/nature.js", "js/track/tracks.js"],     // buildProps calls Scenery*.create (build time, keep ordered)
  ["js/track/scenery/structures.js", "js/track/tracks.js"],
  ["js/track/scenery/city.js", "js/track/tracks.js"],
  ["js/track/scenery/identity.js", "js/track/tracks.js"],
  ["js/track/core/space.js", "js/track/core/surface.js"],
  ["js/track/scenery/models.js", "js/track/scenery/circuit-kit.js"],
  ["js/track/tracks.js", "js/ui/track-maps.js"],               // maps calls Tracks.buildCenterline
  // js/data's own eval-time edges moved to LAZY_DATA_EDGES when the hub left
  // FULL — HARD_EDGES pairs must both be IN FULL to be orderable.
  ["js/physics/consts.js", "js/ui/hud.js"], // hud destructures IDLE_RPM/MAX_RPM at eval
  ["js/camera/mode-switch.js", "js/game.js"],       // game.js destructures CamModes.CAM_MODES at eval
  ["js/data/teams.js", "js/game.js"],            // game.js destructures Teams (DEFAULT_CUSTOM, TIER_V) at eval
  ["js/physics/consts.js", "js/game.js"],  // game.js destructures PhysicsConsts at eval
  ["js/physics/consts.js", "js/physics/body-attitude.js"], // LAT_MAX read at eval
  ["js/data/teams.js", "js/core/store.js"],      // seasonRoster reads Teams (call time, but keep ordered)
  // liverytex kicks off loadLogos(Teams.LIST ids) at EVAL time — it used to
  // carry its own copy of the roster (a SHORT table that had drifted), and
  // reading the real one makes the order load-bearing rather than tidy.
  ["js/data/teams.js", "js/car/liverytex.js"],
  // crestTraced reads CrestPaths at DRAW time, not eval time, so this is not
  // strictly a hard edge — but a mark that silently falls back to the generic
  // monogram because a tag moved is exactly the kind of quiet regression the
  // load-order guard exists to prevent.
  ["js/car/crest-paths.js", "js/car/liverytex.js"],
  ["js/core/store.js", "js/camera/offsets.js"],  // cam-tune destructures GameStore at eval
  ["js/core/store.js", "js/career/career.js"],    // career destructures GameStore at eval
  ["js/core/store.js", "js/career/season-cal.js"], // season-cal destructures GameStore at eval
  ["js/career/season-cal.js", "js/career/season-ui.js"], // the screen reads the season rules
  ["js/career/season-ui.js", "js/game.js"],      // game.js calls SeasonUI.create(G) at eval
  ["js/car/parts.js", "js/career/career.js"],     // Career.start seeds owned/fitted from Parts (call time, keep ordered)
  ["js/data/driver-ratings.js", "js/game.js"],   // makeCars reads DriverRatings for every car's skill
  ["js/career/career.js", "js/race/quali-model.js"],    // quali reads Career.rnd/devFor for its spread
  ["js/physics/aero-zones.js", "js/game.js"],      // game.js calls AeroZones.create(G) at eval time
  ["js/fx/skidmarks.js", "js/game.js"],      // game.js calls SkidMarks.create(G) at eval time
  ["js/race/race-control.js", "js/game.js"],   // game.js calls RaceControl.create(G) at eval time
  ["js/lighting/knobs.js", "js/lighting/track-lights.js"],  // track-lights destructures LightKnobs.LT at eval
  ["js/lighting/knobs.js", "js/lighting/frame-lights.js"],  // frame-lights destructures LightKnobs.LT at eval
  ["js/lighting/knobs.js", "js/lighting/lighting.js"],      // the LightTune façade re-exports TUNE_DEFS/LT at eval
  ["js/lighting/track-lights.js", "js/lighting/lighting.js"],        // …and buildTrackLights/lampStrideNodes
  ["js/lighting/frame-lights.js", "js/lighting/lighting.js"],        // …and setFrameLights/appendCarTailLights
  ["js/lighting/lighting.js", "js/lighting/profiles.js"],  // light-store destructures LightTune's TUNE_DEFS/LT inside create()
  ["js/lighting/profiles.js", "js/game.js"],    // game.js calls LightStore.create(G) at eval time
  ["js/audio/panel.js", "js/game.js"],   // game.js calls AudioPanel.create(G) at eval time
  ["js/ui/scale.js", "js/game.js"],      // game.js calls UiScale.create(G) at eval time
  ["js/career/career.js", "js/race/reliability.js"],  // reliability draws through Career.hash (call time, keep ordered)
  ["js/car/parts.js", "js/race/reliability.js"],    // buildQuality resolves a setup through Parts (call time, keep ordered)
  ["js/race/reliability.js", "js/game.js"],     // game.js validates the stored RELIABILITY level at eval
  ["js/core/mat4.js", "js/physics/ai-drive.js"],         // AiDrive binds M4.clamp/lerp at eval
  ["js/core/mat4.js", "js/physics/brake-cue.js"],        // BrakeCue aliases M4.clamp at eval
  ["js/physics/ai-drive.js", "js/game.js"],         // updateCar calls AiDrive for AI racecraft
  ["js/career/career.js", "js/career/career-ui.js"],  // the screen reads the Career rules
];

// ---------------------------------------------------------------------------
// DEFERRED — js/ files with NO <script> tag, injected at runtime instead.
//
// WHY. GLX (WebGL2) is the shipped renderer; TLX (three.js/TSL) and WGX
// (native WebGPU) are opt-in migrations selected by the localStorage key
// `apex26.gfxBackend`, and (until the boot canary) game.js refused both on
// phones outright. So these
// ~550 KB were parsed and evaluated by essentially every visitor to be used by
// essentially none — a tenth of the whole boot payload, spent on nothing.
//
// The machinery to defer them already existed: game.js resolves `optIn`
// synchronously from localStorage BEFORE it awaits Gfx.create(), and gfx.js
// already treats a missing TLX/WGX global as "not available" and hands the
// caller back to GLX (`typeof TLX === "undefined"` / `typeof WGX ===
// "undefined"`). A failed injection is therefore the same no-op as a browser
// that never had the backend.
//
// KEYED BY the apex26.gfxBackend value that selects the group, and ordered —
// the array IS the load order, and DEFERRED_EDGES below pins the eval-time
// dependencies inside each group the way HARD_EDGES does for FULL.
//
// Adding a file here instead of FULL means: no <script> tag in index.html, and
// it MUST also be seeded into sw.js's OPTIONAL precache set (the service worker
// discovers everything else by parsing the shell's own tags, so a deferred file
// is invisible to it). tests/unit/load-order.test.mjs asserts all three.
// EMPTY since the 2026-09-03 spike-out: WGX and TLX moved to spike/backends/,
// out of the shipped tree (docs/notes/SPIKE-BACKENDS-CHECKLIST.md,
// spike/backends/README.md says how to re-attach). The machinery stays because
// it is what a future deferred file would use; nothing is deferred today.
const DEFERRED = {};

// Eval-time dependencies WITHIN a deferred group — same meaning as HARD_EDGES,
// asserted against that group's own array order. The old edges from wgx.js and
// tlx.js to gfx.js are gone on purpose: gfx.js reads those globals inside
// Gfx.create(), which the loader only reaches after the group has evaluated, so
// the ordering is now enforced by the await rather than by tag position.
// Dev/test surface. No <script> tag, no SW install put (full code cache).
// game.js injects these when wantAgentSurface() — __TEST_MODE, localhost,
// ?apex=1 / ?debug= / ?report=, or apex26.devApi=1. Players on Pages skip
// ~350 KB of parse + PWA memory. Fetch-miss still caches on first use.
const LAZY_AGENT = [
  "js/agent/agentview-raster.js",
  "js/agent/agentview.js",
  "js/agent/apex.js",
];
const LAZY_EDGES = [
  ["js/agent/agentview-raster.js", "js/agent/agentview.js"],
];

// RACE PAYLOAD. Data a session needs only once a race resolves, never to paint
// a menu — so it must not sit in the boot script wall, which is the one perf
// number this box can measure honestly (docs/PERF-FINDINGS.md §0).
// light-presets.js is 338 KB of baked per-condition lighting whose ONLY reader
// is js/lighting/profiles.js, and that reads window.LightPresets at CALL time
// (base()/layers()), not at eval — so an absent file resolves to TUNE_DEFS
// defaults rather than throwing, and game.js re-applies once it lands.
const LAZY_RACE = [
  "js/lighting/presets.js",
];

// THE DATA HUB (js/data/*), 154 KB behind ONE menu button. Jolpica/OpenF1
// schedule, standings, last race, live timing, telemetry and export — none of
// which a session that never opens DATA will run a byte of. Nothing outside
// js/data/ names any of its eight globals except DataHub.init/.open in
// game.js and a `typeof F1API` read in js/agent/apex.js, so the whole directory
// lifts off the boot wall as one bundle loaded from the #mb-data click.
const LAZY_DATA = [
  "js/data/api.js",
  "js/data/telemetry.js",
  "js/data/export.js",
  "js/data/schedule.js",
  "js/data/standings.js",
  "js/data/lastrace.js",
  "js/data/live.js",
  "js/data/hub.js",
];
// hub.js calls Data*.create() at EVAL time, so every tab module must have
// evaluated before it — the same meaning HARD_EDGES carries for FULL. These
// pairs moved here from HARD_EDGES when the directory left FULL, and are
// DERIVED from the roster rather than listed: the shape is "everything, then
// the hub", so a hand-written copy can only ever drift out of step with it.
const LAZY_DATA_EDGES = LAZY_DATA.filter((f) => f !== "js/data/hub.js")
  .map((f) => [f, "js/data/hub.js"]);

// MULTIPLAYER (js/net/*). 241 KB of WebRTC — nostr/rendezvous signalling, SDP,
// QR, the transport, handshake, snapshot codec, session, netplay and the VS
// FRIEND lobby — that a solo session never runs a byte of. The biggest single
// block left on the boot wall, and the one that most players never touch.
//
// Unlike js/data this CANNOT simply be absent: netPlay is called at 20 sites in
// js/game.js and only three of them are `netPlay && …` guarded — netPlay.tick
// is in the frame loop. So game.js holds an INERT STUB from boot and swaps in
// the real objects when VS FRIEND opens; see NET_INERT there, and the guard in
// load-order.test.mjs that derives the stub's required surface from the call
// sites rather than from a hand-written roster.
const LAZY_NET = [
  "js/net/nostr.js",
  "js/net/rendezvous.js",
  "js/net/sdp.js",
  "js/net/qr.js",
  "js/net/scan.js",
  "js/net/transport.js",
  "js/net/handshake.js",
  "js/net/snapshot.js",
  "js/net/session.js",
  "js/net/netplay.js",
  "js/net/lobby.js",
];
// Eval-time pairs, moved verbatim from HARD_EDGES. Listed, not derived: unlike
// the data hub these are a real graph (rendezvous needs nostr, handshake needs
// sdp, session needs snapshot, the lobby needs qr/scan/rendezvous), not one
// module gathering the rest.
const LAZY_NET_EDGES = [
  ["js/net/snapshot.js", "js/net/session.js"],
  ["js/net/sdp.js", "js/net/handshake.js"],
  ["js/net/qr.js", "js/net/lobby.js"],
  ["js/net/rendezvous.js", "js/net/lobby.js"],
  ["js/net/nostr.js", "js/net/rendezvous.js"],
  ["js/net/scan.js", "js/net/lobby.js"],
];

const DEFERRED_EDGES = [];

// Named paths for direct single-file consumers (tests/tools that load one
// source file by path). When a file moves, update it here and every consumer
// follows automatically.
const PATHS = {
  GAME: "js/game.js",                   // the entry: last FULL tag, owner of `const G`
  GLX: "js/render/glx/glx.js",              // the shipped renderer (game-vm.cjs stubs it)
  APEX_API: "js/agent/apex.js",          // the __apex dev API (LAZY_AGENT; game-vm.cjs hooks ApexApi.create)
  TRACKS_ENGINE: "js/track/tracks.js",
  GLX_CHUNKS: "js/render/glx/shaders/glsl-chunks.js",
  LAMP_CHUNKS: "js/render/shared/lamp-chunks.js",
  GLX_SHADERS_LIT: "js/render/glx/shaders/glsl-lit.js",
  GLX_SHADERS_POST: "js/render/glx/shaders/glsl-post.js", // grade/composite GLSL (image-grade-shaders.test.mjs)
  GLTF: "js/render/shared/gltf.js",
  ASSETS: "js/render/shared/assets.js",
  TRACK_SPACE: "js/track/core/space.js",
  TRACK_SURFACE: "js/track/core/surface.js",
  TRACK_MODELS: "js/track/scenery/models.js",
  SCENERY_THEMES: "js/track/scenery/themes.js",
  LANDMARK_KIT: "js/track/scenery/landmark-kit.js",
  CIRCUIT_KIT: "js/track/scenery/circuit-kit.js",
};

const circuitPath = (id) => `${CIRCUITS_DIR}/${id}.js`;
const sceneryPath = (id) => `${SCENERY_DIR}/${id}.js`;

// Files moved by tools/gen/move-tree.mjs, old -> new, kept for ONE release so
// tools/ci/deploy.mjs can name the new path when another session's edit to the
// old one conflicts. Prune entries once every in-flight branch has rebased.
const MOVED = {
  "js/render/webgpu/wgsl-chunks.js": "spike/backends/webgpu/wgsl-chunks.js",
  "js/render/webgpu/wgsl-post.js": "spike/backends/webgpu/wgsl-post.js",
  "js/render/webgpu/wgsl-fx.js": "spike/backends/webgpu/wgsl-fx.js",
  "js/render/webgpu/wgx.js": "spike/backends/webgpu/wgx.js",
  "js/render/three/tsl-chunks.js": "spike/backends/three/tsl-chunks.js",
  "js/render/three/tsl-lit.js": "spike/backends/three/tsl-lit.js",
  "js/render/three/tsl-sky.js": "spike/backends/three/tsl-sky.js",
  "js/render/three/tsl-fx.js": "spike/backends/three/tsl-fx.js",
  "js/render/three/tsl-post.js": "spike/backends/three/tsl-post.js",
  "js/render/three/tlx-shadow.js": "spike/backends/three/tlx-shadow.js",
  "js/render/three/tlx-chunked.js": "spike/backends/three/tlx-chunked.js",
  "js/render/three/tlx-post.js": "spike/backends/three/tlx-post.js",
  "js/render/three/tlx.js": "spike/backends/three/tlx.js",
  "vendor/three-0.185.1/LICENSE.txt": "spike/backends/vendor/three-0.185.1/LICENSE.txt",
  "vendor/three-0.185.1/PATCHES.md": "spike/backends/vendor/three-0.185.1/PATCHES.md",
  "vendor/three-0.185.1/three.core.min.js": "spike/backends/vendor/three-0.185.1/three.core.min.js",
  "vendor/three-0.185.1/three.tsl.min.js": "spike/backends/vendor/three-0.185.1/three.tsl.min.js",
  "vendor/three-0.185.1/three.webgpu.min.js": "spike/backends/vendor/three-0.185.1/three.webgpu.min.js",
  "vendor/three-0.185.1/addons/tsl/display/BloomNode.js": "spike/backends/vendor/three-0.185.1/addons/tsl/display/BloomNode.js",
  "tools/gfx/wgx-capture.mjs": "spike/backends/tools/wgx-capture.mjs",
  "tools/gfx/wgx-lavapipe-probe.mjs": "spike/backends/tools/wgx-lavapipe-probe.mjs",
  "tools/gfx/wgx-shot.mjs": "spike/backends/tools/wgx-shot.mjs",
  "tools/gfx/wgx-validate.mjs": "spike/backends/tools/wgx-validate.mjs",
  "tools/gfx/wgx-vid-repro.mjs": "spike/backends/tools/wgx-vid-repro.mjs",
  "tools/gfx/tlx-pack-check.cjs": "spike/backends/tools/tlx-pack-check.cjs",
  "tools/gfx/wgpu-flag-test.mjs": "spike/backends/tools/wgpu-flag-test.mjs",
  "tools/gfx/gfx-probe.mjs": "spike/backends/tools/gfx-probe.mjs",
  "tools/gfx/road-lut-census.mjs": "spike/backends/tools/road-lut-census.mjs",
  "tests/unit/webgpu-lifecycle.test.mjs": "spike/backends/tests/unit/webgpu-lifecycle.test.mjs",
  "tests/unit/renderer-soft-lifecycle.test.mjs": "spike/backends/tests/unit/renderer-soft-lifecycle.test.mjs",
  "tests/unit/road-lut-frame.test.mjs": "spike/backends/tests/unit/road-lut-frame.test.mjs",
  "tests/specs/tlx-probes.spec.js": "spike/backends/tests/specs/tlx-probes.spec.js",
  "docs/research/WEBGPU-PARITY.md": "spike/backends/docs/WEBGPU-PARITY.md",
  "docs/research/wgx-gallery-manifest.json": "spike/backends/docs/wgx-gallery-manifest.json",
  "docs/research/wgx-gallery/README.md": "spike/backends/docs/wgx-gallery/README.md",
  "docs/research/wgx-gallery/bahrain.png": "spike/backends/docs/wgx-gallery/bahrain.png",
  "docs/research/wgx-gallery/monaco-eye.png": "spike/backends/docs/wgx-gallery/monaco-eye.png",
  "docs/research/wgx-gallery/montreal-eye.png": "spike/backends/docs/wgx-gallery/montreal-eye.png",
  "docs/research/wgx-gallery/montreal.png": "spike/backends/docs/wgx-gallery/montreal.png",
  "docs/research/wgx-gallery/singapore.png": "spike/backends/docs/wgx-gallery/singapore.png",
  "docs/research/wgx-gallery/spa.png": "spike/backends/docs/wgx-gallery/spa.png",
  "docs/research/wgx-gallery/vegas.png": "spike/backends/docs/wgx-gallery/vegas.png",
  ".claude/skills/webgpu-debug/SKILL.md": "spike/backends/skills/webgpu-debug/SKILL.md",
  ".claude/skills/webgpu-debug/references/defects.md": "spike/backends/skills/webgpu-debug/references/defects.md",
  ".cursor/rules/render-wgx.mdc": "spike/backends/skills/cursor-rules/render-wgx.mdc",
  ".cursor/rules/render-tlx.mdc": "spike/backends/skills/cursor-rules/render-tlx.mdc",
  "tools/capture/apex-capture.mjs": "tools/shot/apex-capture.mjs",
  "tools/capture/backend-compare.mjs": "tools/shot/backend-compare.mjs",
  "tools/capture/baked-scenery.mjs": "tools/shot/baked-scenery.mjs",
  "tools/capture/motion-capture.mjs": "tools/shot/motion-capture.mjs",
  "tools/capture/shot.mjs": "tools/shot/shot.mjs",
  "tools/apex-eval.mjs": "tools/shot/apex-eval.mjs",
  "tools/agent.mjs": "tools/shot/agent.mjs",
  "tools/profile-gameloop.mjs": "tools/shot/profile-gameloop.mjs",
  "tools/repro-shot.mjs": "tools/shot/repro-shot.mjs",
  "tools/gfx-probe.mjs": "tools/gfx/gfx-probe.mjs",
  "tools/gpu-census.mjs": "tools/gfx/gpu-census.mjs",
  "tools/gpu-game-check.mjs": "tools/gfx/gpu-game-check.mjs",
  "tools/wgpu-flag-test.mjs": "tools/gfx/wgpu-flag-test.mjs",
  "tools/wgx-capture.mjs": "tools/gfx/wgx-capture.mjs",
  "tools/wgx-lavapipe-probe.mjs": "tools/gfx/wgx-lavapipe-probe.mjs",
  "tools/wgx-shot.mjs": "tools/gfx/wgx-shot.mjs",
  "tools/wgx-validate.mjs": "tools/gfx/wgx-validate.mjs",
  "tools/wgx-vid-repro.mjs": "tools/gfx/wgx-vid-repro.mjs",
  "tools/tlx-pack-check.cjs": "tools/gfx/tlx-pack-check.cjs",
  "tools/road-lut-census.mjs": "tools/gfx/road-lut-census.mjs",
  "tools/glx-call-census.mjs": "tools/gfx/glx-call-census.mjs",
  "tools/ssr-probe.mjs": "tools/gfx/ssr-probe.mjs",
  "tools/gltf-selftest.mjs": "tools/gfx/gltf-selftest.mjs",
  "tools/loop-fault-repro.mjs": "tools/gfx/loop-fault-repro.mjs",
  "tools/chunk-reach.cjs": "tools/gfx/chunk-reach.cjs",
  "tools/chunk-share-census.mjs": "tools/gfx/chunk-share-census.mjs",
  "tools/mcp-cli.mjs": "tools/mcp/mcp-cli.mjs",
  "tools/mcp-smoke.mjs": "tools/mcp/mcp-smoke.mjs",
  "tools/probe-mcp.py": "tools/mcp/probe-mcp.py",
  "tools/tinyfish-mcp.sh": "tools/mcp/tinyfish-mcp.sh",
  "tools/tinyfish-rpc.py": "tools/mcp/tinyfish-rpc.py",
  "tools/chrome-devtools-mcp.sh": "tools/mcp/chrome-devtools-mcp.sh",
  "tools/playwright-mcp.sh": "tools/mcp/playwright-mcp.sh",
  "tools/apex-tools-mcp.mjs": "tools/mcp/apex-tools-mcp.mjs",
  "tools/apex-tools-mcp.sh": "tools/mcp/apex-tools-mcp.sh",
  "tools/apex-tools-mcp.json": "tools/mcp/apex-tools-mcp.json",
  "tools/cdmcp-bg.mjs": "tools/mcp/cdmcp-bg.mjs",
  "tools/cdmcp-cli.py": "tools/mcp/cdmcp-cli.py",
  "tools/cdmcp-lamps.py": "tools/mcp/cdmcp-lamps.py",
  "tools/cdmcp-lamps-tune.py": "tools/mcp/cdmcp-lamps-tune.py",
  "tools/cdmcp-measure.py": "tools/mcp/cdmcp-measure.py",
  "tools/apex-report.js": "tools/mcp/apex-report.js",
  "tools/report-server.mjs": "tools/mcp/report-server.mjs",
  "tools/ui-readable-survey-mcp.py": "tools/mcp/ui-readable-survey-mcp.py",
  "tools/verify-track.cjs": "tools/track/verify-track.cjs",
  "tools/track-verts.cjs": "tools/track/track-verts.cjs",
  "tools/graph-parity.cjs": "tools/track/graph-parity.cjs",
  "tools/float-audit.cjs": "tools/track/float-audit.cjs",
  "tools/float-baseline.json": "tools/track/float-baseline.json",
  "tools/clip-audit.cjs": "tools/track/clip-audit.cjs",
  "tools/clip-baseline.json": "tools/track/clip-baseline.json",
  "tools/coplanar-audit.cjs": "tools/track/coplanar-audit.cjs",
  "tools/coplanar-baseline.json": "tools/track/coplanar-baseline.json",
  "tools/survey-track.mjs": "tools/track/survey-track.mjs",
  "tools/measure-props-over-road.mjs": "tools/track/measure-props-over-road.mjs",
  "tools/startline-probe.cjs": "tools/track/startline-probe.cjs",
  "tools/startline-snap.cjs": "tools/track/startline-snap.cjs",
  "tools/aero-zone-turns.cjs": "tools/track/aero-zone-turns.cjs",
  "tools/rotate-markings.cjs": "tools/track/rotate-markings.cjs",
  "tools/import-circuit-path.mjs": "tools/track/import-circuit-path.mjs",
  "tools/refresh-f1-circuit-reference.mjs": "tools/track/refresh-f1-circuit-reference.mjs",
  "tools/track-accuracy-validator.mjs": "tools/track/track-accuracy-validator.mjs",
  "tools/audit-aero.mjs": "tools/car/audit-aero.mjs",
  "tools/audit-parts.mjs": "tools/car/audit-parts.mjs",
  "tools/parts-sweep.mjs": "tools/car/parts-sweep.mjs",
  "tools/parts-ladder.mjs": "tools/car/parts-ladder.mjs",
  "tools/crest-sweep.mjs": "tools/car/crest-sweep.mjs",
  "tools/logo-authored-sweep.mjs": "tools/car/logo-authored-sweep.mjs",
  "tools/trace-logo.mjs": "tools/car/trace-logo.mjs",
  "tools/cockpit-pale-sweep.mjs": "tools/car/cockpit-pale-sweep.mjs",
  "tools/career-economy.mjs": "tools/car/career-economy.mjs",
  "tools/layout-audit.mjs": "tools/ui/layout-audit.mjs",
  "tools/menu-capture.mjs": "tools/ui/menu-capture.mjs",
  "tools/menu-fit.mjs": "tools/ui/menu-fit.mjs",
  "tools/menu-screens.mjs": "tools/ui/menu-screens.mjs",
  "tools/ui-scale-axis.mjs": "tools/ui/ui-scale-axis.mjs",
  "tools/circuit-axis.mjs": "tools/ui/circuit-axis.mjs",
  "tools/fit-audit.mjs": "tools/ui/fit-audit.mjs",
  "tools/css-play.mjs": "tools/ui/css-play.mjs",
  "tools/lighting-tuner-sweep.mjs": "tools/lighting/lighting-tuner-sweep.mjs",
  "tools/slider-effect.mjs": "tools/lighting/slider-effect.mjs",
  "tools/slider-effect-live.mjs": "tools/lighting/slider-effect-live.mjs",
  "tools/slider-effect-view.py": "tools/lighting/slider-effect-view.py",
  "tools/look-survey-sheet.py": "tools/lighting/look-survey-sheet.py",
  "tools/lighting-campaign/capture.mjs": "tools/lighting/campaign/capture.mjs",
  "tools/lighting-campaign/config.mjs": "tools/lighting/campaign/config.mjs",
  "tools/lighting-campaign/io.mjs": "tools/lighting/campaign/io.mjs",
  "tools/lighting-campaign/metrics.mjs": "tools/lighting/campaign/metrics.mjs",
  "tools/lighting-campaign/tune.mjs": "tools/lighting/campaign/tune.mjs",
  "tools/harness.mjs": "tools/lib/harness.mjs",
  "tools/output-paths.mjs": "tools/lib/output-paths.mjs",
  "tools/game-vm.cjs": "tools/lib/game-vm.cjs",
  "tools/track-build-vm.cjs": "tools/lib/track-build-vm.cjs",
  "tools/webgpu-chrome-args.cjs": "tools/lib/webgpu-chrome-args.cjs",
  "tools/gen-lib.mjs": "tools/gen/gen-lib.mjs",
  "tools/gen-shell.mjs": "tools/gen/gen-shell.mjs",
  "tools/gen-arch-table.mjs": "tools/gen/gen-arch-table.mjs",
  "tools/gen-hooks-table.mjs": "tools/gen/gen-hooks-table.mjs",
  "tools/gen-slider-doc.mjs": "tools/gen/gen-slider-doc.mjs",
  "tools/gen-tools-readme.mjs": "tools/gen/gen-tools-readme.mjs",
  "tools/move-tree.mjs": "tools/gen/move-tree.mjs",
  "tools/assets.mjs": "tools/gen/assets.mjs",
  "tools/import-models.mjs": "tools/gen/import-models.mjs",
  "tools/synth-models.mjs": "tools/gen/synth-models.mjs",
  "tools/bake-elevation.mjs": "tools/gen/bake-elevation.mjs",
  "tools/run-playwright.mjs": "tools/ci/run-playwright.mjs",
  "tools/test-bg.mjs": "tools/ci/test-bg.mjs",
  "tools/test-solo.mjs": "tools/ci/test-solo.mjs",
  "tools/test-shards.sh": "tools/ci/test-shards.sh",
  "tools/tooling-fast.mjs": "tools/ci/tooling-fast.mjs",
  "tools/verify-change.mjs": "tools/ci/verify-change.mjs",
  "tools/pick-tests.mjs": "tools/ci/pick-tests.mjs",
  "tools/select-specs.mjs": "tools/ci/select-specs.mjs",
  "tools/select-budget.mjs": "tools/ci/select-budget.mjs",
  "tools/select-recall.mjs": "tools/ci/select-recall.mjs",
  "tools/junit-failed.mjs": "tools/ci/junit-failed.mjs",
  "tools/ci-coverage.mjs": "tools/ci/ci-coverage.mjs",
  "tools/ci-resolve-before.sh": "tools/ci/ci-resolve-before.sh",
  "tools/ci-select-specs-step.sh": "tools/ci/ci-select-specs-step.sh",
  "tools/test-coverage-audit.mjs": "tools/ci/test-coverage-audit.mjs",
  "tools/test-observed.mjs": "tools/ci/test-observed.mjs",
  "tools/test-honesty.mjs": "tools/ci/test-honesty.mjs",
  "tools/assert-audit.mjs": "tools/ci/assert-audit.mjs",
  "tools/fixture-consumer-audit.mjs": "tools/ci/fixture-consumer-audit.mjs",
  "tools/playwright-occupancy.mjs": "tools/ci/playwright-occupancy.mjs",
  "tools/deploy.mjs": "tools/ci/deploy.mjs",
  "tools/bump-cache.mjs": "tools/ci/bump-cache.mjs",
  "tools/check-gctx.mjs": "tools/check/check-gctx.mjs",
  "tools/scan-globals.mjs": "tools/check/scan-globals.mjs",
  "tools/cross-file-paths.mjs": "tools/check/cross-file-paths.mjs",
  "tools/evaluate-scope-lint.mjs": "tools/check/evaluate-scope-lint.mjs",
  "tools/wait-polling-lint.mjs": "tools/check/wait-polling-lint.mjs",
  "tools/vstd-lint.mjs": "tools/check/vstd-lint.mjs",
  "tools/ratchets.mjs": "tools/check/ratchets.mjs",
  "tools/bloat-scan.mjs": "tools/check/bloat-scan.mjs",
  "tools/trim-comments.mjs": "tools/check/trim-comments.mjs",
  "tools/extract-module.mjs": "tools/check/extract-module.mjs",
  "tools/quick-validate.mjs": "tools/check/quick-validate.mjs",
  "tools/offline-precache-check.cjs": "tools/check/offline-precache-check.cjs",
  "tools/check-physics.mjs": "tools/check/check-physics.mjs",
  "tools/physics-tune-sweep.mjs": "tools/check/physics-tune-sweep.mjs",
  "tools/audio-test.cjs": "tools/check/audio-test.cjs",
  "tools/install-browsers.sh": "tools/env/install-browsers.sh",
  "tools/cloud-agent-install.sh": "tools/env/cloud-agent-install.sh",
  "js/render/lamp-chunks.js": "js/render/shared/lamp-chunks.js",
  "js/render/assets.js": "js/render/shared/assets.js",
  "js/render/gltf.js": "js/render/shared/gltf.js",
  "js/render/glx.js": "js/render/glx/glx.js",
  "js/render/shaders/chunks.js": "js/render/glx/shaders/glsl-chunks.js",
  "js/render/shaders/fx.js": "js/render/glx/shaders/glsl-fx.js",
  "js/render/shaders/lit.js": "js/render/glx/shaders/glsl-lit.js",
  "js/render/shaders/post.js": "js/render/glx/shaders/glsl-post.js",
  "js/render/shaders/sky.js": "js/render/glx/shaders/glsl-sky.js",
  "js/track/spline.js": "js/track/core/spline.js",
  "js/track/mesh.js": "js/track/core/mesh.js",
  "js/track/surface.js": "js/track/core/surface.js",
  "js/track/space.js": "js/track/core/space.js",
  "js/track/geom.js": "js/track/core/geom.js",
  "js/track/scenery-city.js": "js/track/scenery/city.js",
  "js/track/scenery-nature.js": "js/track/scenery/nature.js",
  "js/track/scenery-structures.js": "js/track/scenery/structures.js",
  "js/track/scenery-identity.js": "js/track/scenery/identity.js",
  "js/track/graph.js": "js/track/scenery/graph.js",
  "js/track/models.js": "js/track/scenery/models.js",
  "js/track/themes.js": "js/track/scenery/themes.js",
  "js/track/circuit-kit.js": "js/track/scenery/circuit-kit.js",
  "js/track/landmark-kit.js": "js/track/scenery/landmark-kit.js",
  "js/track/scenery-data.js": "js/track/scenery/data.js",
  "js/game/uilayers.js": "js/ui/layers.js",
  "js/game/topmodal.js": "js/ui/modal.js",
  "js/game/menunav.js": "js/ui/menu-nav.js",
  "js/game/scrollfade.js": "js/ui/scroll-fade.js",
  "js/game/sheetshape.js": "js/ui/sheet-shape.js",
  "js/game/ariastate.js": "js/ui/aria-state.js",
  "js/game/css-zoom.js": "js/ui/css-zoom.js",
  "js/game/hud.js": "js/ui/hud.js",
  "js/game/menus.js": "js/ui/select-screen.js",
  "js/game/results.js": "js/ui/results-sheet.js",
  "js/game/settings-nav.js": "js/ui/settings-tabs.js",
  "js/game/ui-scale.js": "js/ui/scale.js",
  "js/track/maps.js": "js/ui/track-maps.js",
  "js/game/garage-scene.js": "js/garage/scene.js",
  "js/game/setup-ui.js": "js/garage/setup-sheet.js",
  "js/game/carmesh.js": "js/car/car-mesh.js",
  "js/car/teams.js": "js/data/teams.js",
  "js/car/driver-ratings.js": "js/data/driver-ratings.js",
  "js/game/apex.js": "js/agent/apex.js",
  "js/game/agentview.js": "js/agent/agentview.js",
  "js/game/agentview-raster.js": "js/agent/agentview-raster.js",
  "js/game/particles.js": "js/fx/particles.js",
  "js/game/skidmarks.js": "js/fx/skidmarks.js",
  "js/game/quali-sheet.js": "js/ui/quali-sheet.js",
  "js/game/light-store.js": "js/lighting/profiles.js",
  "js/game/light-presets.js": "js/lighting/presets.js",
  "js/game/atmosphere.js": "js/lighting/atmosphere.js",
  "js/game/tuner.js": "js/lighting/tuner-panel.js",
  "js/game/cameras.js": "js/camera/vantage.js",
  "js/game/cam-tune.js": "js/camera/offsets.js",
  "js/game/cam-modes.js": "js/camera/mode-switch.js",
  "js/game/cam-tuner.js": "js/camera/tuner-panel.js",
  "js/game/photomode.js": "js/camera/photo-cam.js",
  "js/game/cockpit-opts.js": "js/camera/cockpit-opts.js",
  "js/game/audio.js": "js/audio/engine.js",
  "js/game/audio-panel.js": "js/audio/panel.js",
  "js/game/music-lib.js": "js/audio/music-lib.js",
  "js/game/spotify.js": "js/audio/spotify.js",
  "js/game/perf.js": "js/perf/governor.js",
  "js/game/loop-health.js": "js/perf/loop-health.js",
  "js/game/gfx-quality.js": "js/perf/quality-preset.js",
  "js/game/metrics.js": "js/perf/metrics-overlay.js",
  "js/game/gfx-debug.js": "js/perf/gfx-debug-overlay.js",
  "js/game/input.js": "js/input/input.js",
  "js/game/steer-tuning.js": "js/input/steer-tuning.js",
  "js/game/lighting-knobs.js": "js/lighting/knobs.js",
  "js/game/track-lights.js": "js/lighting/track-lights.js",
  "js/game/frame-lights.js": "js/lighting/frame-lights.js",
  "js/game/lighting.js": "js/lighting/lighting.js",
  "js/game/renderer-picker.js": "js/perf/renderer-picker.js",
  "js/log.js": "js/core/log.js",
  "js/mat4.js": "js/core/mat4.js",
  "js/game/store.js": "js/core/store.js",
  "js/game/physics-consts.js": "js/physics/consts.js",
  "js/game/ai-drive.js": "js/physics/ai-drive.js",
  "js/game/aerozones.js": "js/physics/aero-zones.js",
  "js/game/bodyattitude.js": "js/physics/body-attitude.js",
  "js/game/brake-cue.js": "js/physics/brake-cue.js",
  "js/game/debrisworld.js": "js/physics/debris-world.js",
  "js/game/incidentsim.js": "js/physics/incident-sim.js",
  "js/game/racecontrol.js": "js/race/race-control.js",
  "js/game/reliability.js": "js/race/reliability.js",
  "js/game/career.js": "js/career/career.js",
  "js/game/career-ui.js": "js/career/career-ui.js",
  "js/game/season-cal.js": "js/career/season-cal.js",
  "js/game/season-ui.js": "js/career/season-ui.js",
  "js/game/quali.js": "js/race/quali-model.js",
};

module.exports = {
  MOVED,
  CIRCUITS, CIRCUITS_DIR, FULL, CSS, CSS_PRELOAD, CSS_DEFERRED, SHELL_NOTES, CARVIEW, TRACK_VM, HARD_EDGES,
  DEFERRED, DEFERRED_EDGES, LAZY_AGENT, LAZY_EDGES, LAZY_RACE,
  LAZY_DATA, LAZY_DATA_EDGES, LAZY_NET, LAZY_NET_EDGES,
  SCENERY_DIR, LAZY_SCENERY, sceneryPath,
  PATHS, circuitPath,
};
