/**
 * The title-screen car art is generated by tools/gen/title-art.mjs into the
 * @gen-shell:title-art block of index.html. Nothing in tests/ looked at it, so
 * every invariant the drawing depends on was enforced only by eye — and the one
 * pixel golden that covers it (menu-baseline.spec.js) is a browser group that
 * does not run on a docs-and-tools change.
 *
 * These are the structural facts a redraw must not break. They are cheap, they
 * run in the fast tier, and each one is a mistake that was actually made.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const SHELL = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
const CSS = fs.readFileSync(path.join(ROOT, "css", "menus.css"), "utf8");

const OPEN = "<!-- @gen-shell:title-art -->";
const CLOSE = "<!-- @gen-shell:/title-art -->";
const ART = SHELL.slice(SHELL.indexOf(OPEN) + OPEN.length, SHELL.indexOf(CLOSE));
const DRAWINGS = [["the landscape drawing", ART]];

test("the art lives in a generated block", () => {
  assert.ok(SHELL.includes(OPEN) && SHELL.includes(CLOSE),
    "index.html lost the @gen-shell:title-art markers — tools/gen/title-art.mjs writes between them");
  assert.ok(ART.includes('<g transform='), "the block no longer holds the placed art group");
});

test("every path is closed or explicitly fill:none", () => {
  // A FILLED path is a MASS: it hides what is behind it, and that occlusion is
  // the whole depth cue. An open path with the group's fill would smear a
  // wedge across the car, so open runs carry fill="none" directly (a direct
  // declaration beats an inherited one).
  for (const g of ART.split("<g ").slice(1)) {
    const open = g.includes('<path fill="none"');
    for (const d of g.match(/ d="([^"]+)"/g) || []) {
      const closed = d.trimEnd().endsWith('Z"');
      assert.ok(closed || open,
        `an open subpath is drawn without fill="none": ${d.slice(0, 60)}…`);
    }
  }
});

test("the placed art lands inside its own viewBox", () => {
  // The drawing is built in metres through a pinhole camera and then placed
  // with one translate+scale, so a camera or scale change moves the WHOLE car
  // at once and can walk it out of frame without any single coordinate looking
  // wrong. The trails deliberately run off to the right, so this asks that the
  // bulk is in shot, not that every mark is.
  // Scan from the END of the placed group's own tag, not from the block's first
  // ">": #tc-frame wraps the placement now, so a first-">" slice swallowed
  // "translate(202 675)" as if it were a point and read the car's feet at 1343.
  const open = ART.match(/<g transform="translate\((-?[\d.]+) (-?[\d.]+)\) scale\(([\d.]+)\)">/);
  const [, tx, ty, sc] = open;
  const [X, Y, S] = [Number(tx), Number(ty), Number(sc)];
  const pts = [...ART.slice(open.index + open[0].length).matchAll(/(-?\d+) (-?\d+)/g)]
    .map((m) => [X + Number(m[1]) * S, Y + Number(m[2]) * S]);
  assert.ok(pts.length > 500, "the art lost almost all of its geometry");
  const inside = pts.filter(([x, y]) => x >= 0 && x <= 1400 && y >= 0 && y <= 900).length;
  const frac = inside / pts.length;
  assert.ok(frac > 0.9, `only ${(frac * 100).toFixed(1)} % of the art is inside the 1400x900 viewBox`);
  const lowest = Math.max(...pts.map((p) => p[1]));
  assert.ok(lowest <= 900, `the car's feet sit at y ${lowest.toFixed(0)}, below the frame`);
});

test("the fade rides on stroke-opacity, never on the group", () => {
  // `opacity` on a group makes its FILLS translucent too and the car collapses
  // into a wireframe. Six drafts died this way.
  assert.equal(/<g [^>]*\sopacity=/.test(ART), false,
    "a group carries plain `opacity` — use stroke-opacity or fill-opacity");
});

test("the trail colour comes from a CSS rule, not a presentation attribute", () => {
  // A presentation attribute has specificity 0, so `fill="url(#tc-trail)"` on
  // the group LOSES to `#title-car g { fill: var(--carbon) }` and the tyre
  // marks silently render as bodywork. The data-trail hook exists to win.
  for (const [name, block] of DRAWINGS) {
    assert.ok(block.includes("<g data-trail"), `${name} lost its data-trail hook`);
    assert.equal(/<g data-trail[^>]*fill="url\(/.test(block), false,
      `${name}: the trail fill is a presentation attribute again — it will lose to the group rule`);
  }
  assert.ok(/#title-car\)?\s*g\[data-trail\]\s*\{[^}]*fill:\s*url\(#tc-trail\)/.test(CSS),
    "css/menus.css lost the [data-trail] fill rule for the landscape drawing");
});

test("one drawing serves every shape, laid out per shape", () => {
  // A second, top-down drawing for tall screens lived beside this one until
  // 2026-09-24. Once the portrait phone and the tall tablet both took the side
  // view into their own grid band it was shown nowhere, yet every visitor still
  // downloaded its 24 KB. Tall shapes turn the full-screen layer off and each
  // portrait block puts #title-car back in row 3.
  assert.doesNotMatch(SHELL, /id="title-car-top"|@gen-shell:title-art-top/,
    "a second title drawing is back in the shell — is anything showing it?");
  assert.ok(/\[data-shape="tall"\]\)? ?#title-car \{ display: none/.test(CSS),
    "the tall shape no longer turns off the full-screen art layer");
  const bands = [...CSS.matchAll(/\[data-shape="tall"\]\) #title-car \{\s*display: block;[^}]*grid-row: 3/g)];
  assert.equal(bands.length, 2, "the portrait phone and the tall tablet should each put #title-car in row 3");
});

test("every gradient the art references is defined", () => {
  const defined = new Set([...SHELL.matchAll(/<linearGradient id="(tc-[\w-]+)"/g)].map((m) => m[1]));
  for (const [, id] of ART.matchAll(/url\(#(tc-[\w-]+)\)/g)) {
    assert.ok(defined.has(id), `the art references #${id}, which <defs> does not define`);
  }
});

test("the box carries the viewBox's own aspect", () => {
  // preserveAspectRatio alone does not size the ELEMENT. Without an explicit
  // aspect-ratio the art blew up to 1857 px wide on an iPad in portrait, at
  // full opacity, because the >1000px fade never fired.
  assert.ok(/#title-car\s*\{[^}]*aspect-ratio:\s*1400\s*\/\s*900/.test(CSS),
    "#title-car lost `aspect-ratio: 1400 / 900` and will size itself off its parent");
});

test("every art group carries its reveal stage and order", () => {
  // The draw-on animation keys on these: data-stage picks WHAT animates,
  // --i staggers WHEN. An art group (one holding a <path> directly) without
  // them simply pops in un-animated, which no static check would ever notice.
  const STAGES = new Set(["ink", "body", "tone", "detail", "brush", "trail"]);
  for (const [name, block] of DRAWINGS) {
    const groups = [...block.matchAll(/<g ([^>]*)><path /g)].map((m) => m[1]);
    assert.ok(groups.length > 5, `${name} lost its art groups`);
    const order = [];
    for (const attrs of groups) {
      const stage = attrs.match(/data-stage="(\w+)"/);
      const i = attrs.match(/style="--i:(\d+)"/);
      assert.ok(stage && STAGES.has(stage[1]), `${name}: <g ${attrs.slice(0, 60)}> has no known data-stage`);
      assert.ok(i, `${name}: <g ${attrs.slice(0, 60)}> has no --i`);
      order.push([stage[1], Number(i[1])]);
      // The stage must agree with the hook the CSS paints it by.
      if (/data-trail/.test(attrs)) assert.equal(stage[1], "trail");
      if (/data-tone/.test(attrs)) assert.equal(stage[1], "tone");
      if (/data-ink/.test(attrs)) assert.equal(stage[1], /stroke="none"/.test(attrs) ? "brush" : "ink");
    }
    // --i is a permutation of 0..n-1, and the trails draw on LAST.
    const idx = order.map(([, i]) => i).sort((a, b) => a - b);
    assert.deepEqual(idx, idx.map((_, k) => k), `${name}: --i is not 0..${idx.length - 1} without gaps`);
    const trails = order.filter(([s]) => s === "trail").map(([, i]) => i);
    const rest = order.filter(([s]) => s !== "trail").map(([, i]) => i);
    assert.ok(trails.length && Math.min(...trails) > Math.max(...rest), `${name}: the trails do not reveal last`);
  }
});

test("no path carries pathLength", () => {
  // The outlines reveal with a clip-path wipe on their GROUP (css/menus.css).
  // A dash draw-on was tried and cannot trace these paths: each is many
  // subpaths, and the dash pattern restarts at every M, so they all popped.
  for (const [name, block] of DRAWINGS) {
    assert.doesNotMatch(block, /pathLength/, `${name}: pathLength is back — the draw is a group wipe, not a dash`);
  }
});
